// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUCpYe70WHYyyLAgDuC1oxodWlb9ri2WM',
    appId: '1:736869811755:web:c6cde74eb7621648ed0c6e',
    messagingSenderId: '736869811755',
    projectId: 'marapiapp',
    authDomain: 'marapiapp.firebaseapp.com',
    storageBucket: 'marapiapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVxr1xq4cAMIoKC_BtG6HFrLHFxR0AV0Y',
    appId: '1:736869811755:android:9366aef20595d507ed0c6e',
    messagingSenderId: '736869811755',
    projectId: 'marapiapp',
    storageBucket: 'marapiapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvsmTbbnQvFNII5Z8tyxMhlNTnYo6e98g',
    appId: '1:736869811755:ios:be4f217cc03fe160ed0c6e',
    messagingSenderId: '736869811755',
    projectId: 'marapiapp',
    storageBucket: 'marapiapp.firebasestorage.app',
    iosBundleId: 'com.example.mea',
  );
}
